### ISSUE TITLE
Open story in app

### ISSUE THREAD

**Issue by gredman** [anosidium/HacKit-Feedback-And-Support#15]
Maybe I’m missing something, but I would love if I could read linked stories in the app. Currently I have to open the story/comments, click the link and switch over to Safari, then switch back to HacKit for the comments.

Other than that, great app!

**Comment by anosidium** [comment]
Thank you for your feedback and I am glad to know that you like the app! This feature has been [asked before](https://github.com/anosidium/HacKit-Feedback-And-Support/issues/4#issue-920751635) and the explanation is provided [there](https://github.com/anosidium/HacKit-Feedback-And-Support/issues/4#issuecomment-903301410) too.

**Comment by gredman** [comment]
Fair enough! Thanks for the explanation.
