### ISSUE TITLE
Add an option to limit posts to 30

### ISSUE THREAD

**Issue by arjunbajaj** [anosidium/HacKit-Feedback-And-Support#16]
Just like HN, it would be nice if only the top 30 posts are shown, to avoid information overload. An option in the settings would be nice.

**Comment by anosidium** [comment]
It actually does that for every category you select.

**Comment by arjunbajaj** [comment]
Scrolling to the end of the list loads another 30 posts. There should be an option to disable infinite scrolling.

**Comment by anosidium** [comment]
So basically you want it paginated like the main website?

**Comment by arjunbajaj** [comment]
Yes, an option to enable pagination would be good. Perhaps with a setting to set how many posts to load per "page" (default 30).
