### ISSUE TITLE
Search results issues

### ISSUE THREAD

**Issue by gingerbeardman** [anosidium/HacKit-Feedback-And-Support#20]
See below for revised description

https://github.com/anosidium/HacKit-Feedback-And-Support/issues/20#issuecomment-1566211091

**Comment by anosidium** [comment]
I'm not entirely clear about this, could you please explain in more details? Are you suggesting that the results are duplicated?  What's special about story no. 32? I don't see duplicated results in the screenshot.

**Comment by gingerbeardman** [comment]
Yes, results are duplicated.

Of course I cannot show bottom and top of the search results in HacKit at the same time.

Search results (31 items): https://hn.algolia.com/?q=great+wave

Scrolling to the bottom of those 31 items in HacKit makes the results start again.

result 31: 11 years ago
result 32: 1 week ago

Please try this search yourself!

**Comment by gingerbeardman** [comment]
here is a screen recording.

notice how the page number and quantity of search results grows as I scroll down the list.

https://github.com/anosidium/HacKit-Feedback-And-Support/assets/49612/3c4d007d-ab45-493d-a4ab-5d000f4c2156

**Comment by gingerbeardman** [comment]
Hmm, I see what you mean, these may not be duplicates but multiple submissions of the same URLs.

But there is some difference in search results

Searching for "great wave" (with quotes) https://hn.algolia.com/?dateRange=all&page=0&prefix=false&query=%22great%20wave%22&sort=byPopularity&type=story
- 25 results

HacKit
- 25 results in label
- 38 items in list

![Screen shot 2023-05-28 at 18 47 08](https://github.com/anosidium/HacKit-Feedback-And-Support/assets/49612/b003c0d0-9798-4bbf-861c-db9dad6ca679)

**Comment by anosidium** [comment]
Thank you very much for the detailed report. It is very helpful. I could not quite match your screenshot as it stopped at story no. 26 which appears to be posted from your Hacker News account, [msephton](https://news.ycombinator.com/user?id=msephton).

But I do see the issues and I will fix this in the next update. I was wondering if you have a search term with a few pages result? "great wave" produced one page result.

**Comment by gingerbeardman** [comment]
Thanks!

Search query with 8 pages: "playdate" (with quotes)

https://hn.algolia.com/?dateRange=all&page=7&prefix=false&query=%22Playdate%22&sort=byPopularity&type=story

**Comment by anosidium** [comment]
I have uploaded a TestFlight build which fixed this. You might want to [test](https://testflight.apple.com/join/lJyZPVGl) it, if you do, you should backup the cache as a precaution.

**Comment by anosidium** [comment]
I thought I would let you know that the version 3.3 update is now live on the App Store.

**Comment by gingerbeardman** [comment]
Thanks, I have been using the TestFlight with no issues! Will transition back to App Store version.
