### ISSUE TITLE
macOS Sequoia - 15.1 Beta (24B5024e) - not able to see any of the stories

### ISSUE THREAD

**Issue by firefoxNX** [anosidium/HacKit-Feedback-And-Support#22]
On macOS Sequoia - 15.1 Beta (24B5024e) - not able to see any of the stories

I tried HacKit Settings - Reset, Delete. But did not make a difference.

![CleanShot 2024-08-15 at 14 43 22@2x](https://github.com/user-attachments/assets/da821e3b-d62e-4eef-b69a-7e7ae5ffa681)

**Comment by anosidium** [comment]
I see that you are running HacKit on macOS Sequoia, which is currently in beta. I don't have a computer to test it on Sequoia. So a number of things you could try to resolve it:

- Update to the latest version of HacKit.
- In stories list, does the loading icon show? Is it the same in other categories?
- In your user Library folder, not your System Library folder. Find HacKit inside Containers folder and traverse the folder in Data/Library/Application Support/HacKit and delete the files in there. There should be three files.

**Comment by firefoxNX** [comment]
- I am using Version 3.4 (31)
- When starting the application I see loading icon. I don't see loading icon when selecting other categories. Using Proxyman I can see network calls are being made to hacker-news.firebaseio.com
- I tried deleting the 3 files in '/Users/uname/Library/Containers/uk.co.anosidium.HacKit.macos/Data/Library/Application Support/HacKit' and also '/Users/uname/Library/Containers/uk.co.anosidium.HacKit.macos' but it did not make a difference.

It was working fine in previous macOS Sequoia 15 Beta.

**Comment by anosidium** [comment]
Are you by any chance running a Hackintosh?

I've checked the release notes for Sequoia and I didn't find anything that I think could possibly break HacKit. I suppose you could rollback to the previous version of Sequoia or wait for the next update.

You could try checking your firewall settings to see if it is restricting network access for HacKit? Try a different network if you can?

I'm afraid that I don't have access to Sequoia to debug the app so I can't find out why it is not working as expected but then it is a beta and sometimes things break.

**Comment by Jason-Abbott** [comment]
I have the same problem on a Mac Studio and MacBook Air. Both are now running MacOS 15 RC and HacKit 3.4 (31). 

I also have tried re-installing, option-starting it, etc.

<img width="659" alt="image" src="https://github.com/user-attachments/assets/5139df5c-ccd1-4bca-a6c6-6b323f1962df">

**Comment by firefoxNX** [comment]
Thanks @Jason-Abbott. Good to know I was not the only one facing this issue.
I am using Macbook Pro M3 Max running macOS 15.1 Sequoia (24B5035e)

**Comment by Jason-Abbott** [comment]
Also, if I click the `Fonts & Colour` setting, it is blank and then the `General` setting also becomes unviewable

<img width="389" alt="image" src="https://github.com/user-attachments/assets/0f1114b5-019a-490d-bb94-d1660d78d959">

**Comment by Jason-Abbott** [comment]
Oh, one other data point: I have another MacBook still on 14.6.1. HacKit works fine there, meaning same network, etc.

**Comment by anosidium** [comment]
Now that macOS Sequoia is officially out. Do these problems still persist?

**Comment by firefoxNX** [comment]
I am on 15.1 Beta (24B5046f). 

With Parallels running 15.0 virtual machine I am unable to login to the Mac App Store. Getting error - An unknown error occurred.

**Comment by firefoxNX** [comment]
It is not working.

I was able to copy Hackit.app over to the macOS 15.0 (24A335) VM

![CleanShot 2024-09-20 at 13 15 11@2x](https://github.com/user-attachments/assets/3c8556cb-5ce2-4737-80d0-d0897763eb07)

**Comment by anosidium** [comment]
1. What happens when you run it on the operating system as opposed through virtualisation?
2. Why run it through virtualisation?
3. Are you running macOS on a Hackintosh?

I can't do much about it until I upgrade to Sequoia.

**Comment by firefoxNX** [comment]
1. Running on macOS Sequoia - not seeing any items in the list
2. To try GA version
3. No. I am not running Hackintosh.

**Comment by 3zero2** [comment]
> Now that macOS Sequoia is officially out. Do these problems still persist?

Yes. I'm on the official release and the problems persist.

**Comment by anosidium** [comment]
So, I bought an Apple Silicon Mac and it is running macOS Sequoia and I ran into same the issues. Are there any other issues you might have found? As far as I know is that stories are not being displayed and the settings window does not display the panes properly. I will try to fix it, please bear with me.

Is anybody running macOS Sequoia on an Intel Mac? Do the problems persist?

> 2. To try GA version

What's GA?

**Comment by Jason-Abbott** [comment]
Glad you’re able to see the issue now. I think you’ll be able to fix it quickly. 🙂

GA is an abbreviation for “General Availability” which means the release version of a product, not the beta.

**Comment by firefoxNX** [comment]
Seeing the same issue on Intel Mac as well.

**Comment by anosidium** [comment]
Psst!

<img width="1710" alt="Screenshot 2024-10-02 at 7 11 36 pm" src="https://github.com/user-attachments/assets/876fed14-e2c9-4784-9a3d-0ebcbe00e484">

![Screen Recording 2024-10-02 at 7 14 28 pm](https://github.com/user-attachments/assets/feed5a0f-fba1-4d4a-8618-1dd915eaa0db)

**Comment by anosidium** [comment]
The update will be on the App Store soon!

<img width="1710" alt="Original 5" src="https://github.com/user-attachments/assets/46061b12-f595-4cc5-b20c-d76e2dc2eefb">

**Comment by anosidium** [comment]
Released HacKit 3.5 to address the issues.
