### ISSUE TITLE
Support installation via brew

### ISSUE THREAD

**Issue by tillepille** [anosidium/HacKit-Feedback-And-Support#3]
It would be great to install and manage the App alternatively via the infamous [brew](https://brew.sh/) project.

**Comment by anosidium** [comment]
Thank you for your suggestion. Could you please tell me why? Homebrew is typically used for command line.

**Comment by tillepille** [comment]
Yes but with [casks](https://formulae.brew.sh/cask/) there are also a bunch of 'real' apps available to manage over brew.

My usecase is, that I do not have an Apple ID (because I can't or i don't want to) on my work laptop, therefore I cant use the AppStore.
With Brew there's a file called brewfile wich holds all your installed binarys and casks and you can easily transfer that to a new device and install all your apps with one command `brew bundle install`.

**Comment by anosidium** [comment]
Oh I see. Currently I don't have plans to distribute outside the App Store.
