### ISSUE TITLE
Render links inside HacKit

### ISSUE THREAD

**Issue by ericschmar** [anosidium/HacKit-Feedback-And-Support#4]
Please consider adding a section to the content view to render links inside Hackit instead of opening in a separate browser. Part of the reason this project was exciting was to get a MacOS native experience while browsing Hacker News, but it is tedious to go back and forth between Hackit and whatever browser I use.

**Comment by anosidium** [comment]
Thank you for your suggestion. Are you basically asking to have a browser integrated into HacKit?

**Comment by ericschmar** [comment]
yea that would be ideal. otherwise I would be switching between app and browser to view the actual content

**Comment by anosidium** [comment]
Thank you for clarifying. Mac apps usually do not come with an integrated browser, it is mostly an iOS convention. Usually, when there is a link, it opens the user's preferred browser. I am afraid, I will not implement it as it is not conventional.

**Comment by ericschmar** [comment]
Understood. Thanks for taking the time to explain!
