### ISSUE TITLE
Color code vertical lines by comment depth

### ISSUE THREAD

**Issue by NilsEnevoldsen** [anosidium/HacKit-Feedback-And-Support#7]
Color code the vertical lines to the left of comments by comment depth.

This should probably be an opt-in user preference if it is added.

Apollo (an iOS Reddit client) does this, and (for me) it makes comment threads easier to visually parse.

**Comment by anosidium** [comment]
Thank you for the suggestion. This is something I could implement. Could you please post a screenshot of Apollo comment threads?

**Comment by NilsEnevoldsen** [comment]
Example Apollo comment thread on the left (with some collapsed comments).

Apollo color scheme preferences on the right. I believe “Rainbow” is the default, but I'm not sure.

<img src="https://user-images.githubusercontent.com/222743/128902899-40fc9ce2-7414-4c0b-aaba-8eb6818f4eec.png" width=25%><img src="https://user-images.githubusercontent.com/222743/128900771-17f1d903-bc94-4c6e-9a6d-798f32d5baf4.png" width=25%>

<img src="https://user-images.githubusercontent.com/222743/128903661-e5fe9b80-f155-4489-b578-6522643868bf.png" width=25%><img src="https://user-images.githubusercontent.com/222743/128903490-f9866410-cd9e-4411-8191-617f9dcdaf04.png" width=25%>

**Comment by anosidium** [comment]
Thank you very much for the screenshots. I appreciate that you included the dark appearance screenshots. Are the colours randomised in the comment threads or do they follow the theme colour order in settings?

**Comment by NilsEnevoldsen** [comment]
They follow the order in settings, which is important. The monohue gradients would look very odd if the order were randomized, I think. 

The top level comments aren't colored, only children. I haven't considered whether that would be desirable in HacKit.

**Comment by anosidium** [comment]
Thank you for confirming. I am curious about this, what happen in a very long comment threads where there are many replies, one after another. The theme colour sequence, does it repeat from the beginning?

For rainbow theme, ROYGBIV > ROYGBIV > ROYGBIV > ...

I will implement this. I can't promise you that it will be in the next update but I have added it to my roadmap.

**Comment by NilsEnevoldsen** [comment]
Yes, in the case of deep comment threads, the colors start again from the beginning.

**Comment by anosidium** [comment]
Psst!

<img width="1264" alt="Screenshot 2021-08-23 at 12 10 06 AM" src="https://user-images.githubusercontent.com/39738481/130372946-6c03b50a-42a9-434f-a4df-10f9e33ca9ef.png">

**Comment by NilsEnevoldsen** [comment]
Looks great to me. I hope others will find it as nice as I do.

**Comment by anosidium** [comment]
I thought I would personally let you know that I am releasing an update on the 20th September 2021, so please forward to have this feature to your delight!
