### ISSUE TITLE
Cache comment threads

### ISSUE THREAD

**Issue by NilsEnevoldsen** [anosidium/HacKit-Feedback-And-Support#8]
What happens:
1. Open story A
2. Spinner
3. Comment thread loads
4. Wait 1 second
5. Open story B
6. Spinner
7. Comment thread loads
8. Wait 1 second
9. Open story A
10. Spinner
11. Comment thread loads

Opening story A the second time should be instant. Since it's only been a few seconds, and I haven't requested a refresh of the thread, it's very unlikely that I care about refreshing the comment thread.

**Comment by anosidium** [comment]
Did you know that you can open the story in a separate window (⌘O) as the comments will only load once? You can manually refresh it whenever you want.

One of the advantages of HacKit being a macOS app compared to iOS apps is that it supports multiple windows and tabs.

**Comment by anosidium** [comment]
I thought I would personally inform you that the next version of HacKit persist comments. You can try a beta version on [TestFlight](https://testflight.apple.com/join/lJyZPVGl). I would like to know what you think about it.
